[package]
authors = ['Mangata team']
name = "rolldown-runtime-api"
version = "2.0.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]

sp-api = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }

[features]
default = ["std"]

std = [
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
]
