[package]
name = "sc-basic-authorship"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Basic implementation of block-authoring logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }
futures = "0.3.4"
futures-timer = "3.0.1"
log = "0.4.8"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.8.0"}
sp-api = { version = "2.0.0"}
sp-runtime = { version = "2.0.0", path = "/home/dev/mangata-node/primitives/runtime/" }
sp-core = { version="2.0.0"}
sp-blockchain = { version = "2.0.0"}
sc-client-api = { version = "2.0.0"}
sp-consensus = { version = "0.8.0"}
sp-inherents = { version = "2.0.0"}
sc-telemetry = { version = "2.0.0"}
sp-transaction-pool = { version = "2.0.0"}
sc-block-builder = { version = "0.8.0", path = "../block-builder" }
extrinsic-info-runtime-api = { version = "2.0.0", path = "../../primitives/extrinsic-info-runtime-api" }
sc-proposer-metrics = { version = "0.8.0"}
tokio-executor = { version = "0.2.0-alpha.6", features = ["blocking"] }
sc-transaction-pool = { path='../transaction-pool', version = "2.0.0"}

[dev-dependencies]
parking_lot = "0.10.0"
pallet-random-seed = { path = "../../pallets/random-seed", version = "2.0.0" }
substrate-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }
sp-ignore-tx = { "version" = "2.0.0", path = "../../primitives/ignore-tx" }
