[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../../parity/polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=trace" ]
# chain = "westend-local"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    rpc_port = 9944

    [[relaychain.nodes]]
    name = "bob"

[[parachains]]
id = 2110
cumulus_based = true
chain = "rococo-local"

    [[parachains.collators]]
    name = "alice"
    command = "./target/debug/mangata-node"
    rpc_port = 9946
	args = [ "-lblock_builder=trace,basic-authorship=trace,slots=trace,aura=trace,cumulus=trace,relay=trace" ]

    [[parachains.collators]]
    name = "bob"
    command = "./target/debug/mangata-node"
