[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../parity/polkadot/target/release/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9944

    [[relaychain.nodes]]
    name = "bob"

[[parachains]]
id = 2114
cumulus_based = true
chain = "turing-dev"

    [[parachains.collators]]
    name = "alice"
    command = "../OAK-blockchain/target/release/oak-collator"
    ws_port = 9947
    rpc_port = 8855

    [[parachains.collators]]
    name = "bob"
    command = "../OAK-blockchain/target/release/oak-collator"

[[parachains]]
id = 2110
cumulus_based = true
chain = "mangata-rococo-local"

    [[parachains.collators]]
    name = "alice"
    command = "./target/release/mangata-node"
    ws_port = 9946
    rpc_port = 8866

    [[parachains.collators]]
    name = "bob"
    command = "./target/release/mangata-node"

[[hrmp_channels]]
sender = 2114
recipient = 2110
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2110
recipient = 2114
max_capacity = 8
max_message_size = 512
