[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../parity/polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"
	validator = true
	ws_port = 9944

	[[relaychain.nodes]]
	name = "bob"
	validator = true

[[parachains]]
id = 1000
chain = "statemine-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	command = "../parity/cumulus/target/release/polkadot-parachain"
	args = ["-lxcm=trace"]
	ws_port = 9948

	# run bob as parachain collator
	# [[parachains.collators]]
	# name = "bob"
	# validator = true
	# command = "../parity/cumulus/target/release/polkadot-parachain"
	# args = ["-lparachain=debug"]

[[parachains]]
id = 2110
chain = "mangata-rococo-local"
cumulus_based = true

	[[parachains.collators]]
	name = "alice"
	command = "./target/release/mangata-node"
	args = ["-lxcm=trace --force-authoring"]
	ws_port = 9946

	# [[parachains.collators]]
	# name = "bob"
	# command = "./target/release/mangata-node"

[[hrmp_channels]]
sender = 1000
recipient = 2110
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 2110
recipient = 1000
max_capacity = 8
max_message_size = 512
