[settings]
provider = "native"
timeout = 1000

[relaychain]
default_command = "../parity/polkadot/target/release/polkadot"
chain = "westend-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9944

    [[relaychain.nodes]]
    name = "bob"

[[parachains]]
id = 2110
cumulus_based = true
chain = "mangata-rococo-local-testnet"

    [[parachains.collators]]
    name = "alice"
    command = "./target/release/mangata-node"
    ws_port = 9946
    rpc_port = 8866

    # [[parachains.collators]]
    # name = "bob"
    # command = "./target/release/mangata-node"