nodeChain: mangata-rococo-local
enableLocalRelaychain: true
enableParachainRegisterSidecar: true
enableServiceMonitorCollectors: false
storageSize: 20Gi
relaychainImage: parity/polkadot:v1.1.0
relaychainStorageSize: 20Gi
relaychainBootnodeAddr: /dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

# Correspond to `pd-balanced` storage type in GCP
# Will delete volume on PVC resource deletion
storageClass: node-data-volume

node01:
  isCollator: true
  bootnodeAddr: ''
  accountKeySeed: '0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a'
  nodeKey: '0000000000000000000000000000000000000000000000000000000000000003'

node02:
  isCollator: true
  bootnodeAddr: /dns4/node-01-p2p/tcp/30333/p2p/12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x
  accountKeySeed: '0x398f0c28f98885e046333d4a41c19cee4c37368a9832c6502f6cfd182e2aef89'
  nodeKey: '0000000000000000000000000000000000000000000000000000000000000004'

resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 4Gi
