enableLocalRelaychain: true
enableParachainRegisterSidecar: true
enableServiceMonitorCollectors: false
storageSize: 5Gi
relaychainImage: parity/polkadot:v0.9.38
relaychainStorageSize: 5Gi
relaychainBootnodeAddr: /dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp

# Correspond to `pd-balanced` storage type in GCP
# Will delete volume on PVC resource deletion
storageClass: node-data-volume

node01:
  isCollator: true
  bootnodeAddr: ''
  accountKeySeed: ref+gcpsecrets://direct-pixel-353917/node-01-key-seed-dev
  nodeKey: '0000000000000000000000000000000000000000000000000000000000000003'

node02:
  isCollator: true
  bootnodeAddr: /dns4/node-01-p2p/tcp/30333/p2p/12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x
  accountKeySeed: ref+gcpsecrets://direct-pixel-353917/node-02-key-seed-dev
  nodeKey: '0000000000000000000000000000000000000000000000000000000000000004'

resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 4Gi
