[package]
name = "pallet-staking"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-std = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-npos-elections = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-io ={ version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-runtime = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-staking = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-support = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-system = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-session = { version = "2.0.0", default-features = false, features = ["historical"] , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-authorship = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-application-crypto = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-xyk = { version = "0.1.0", default-features = false, path = "../xyk" }
orml-tokens = { version = "0.3.1", default-features=false, git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }
mangata-primitives = { path = '../../primitives/mangata', default-features = false, version = '0.1.0' }
sp-core = { version = "2.0.0", default-features = false , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }

# Optional imports for benchmarking
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
sp-storage = { version = "2.0.0" , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
sp-tracing = { version = "2.0.0" , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-balances = { version = "2.0.0" , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-timestamp = { version = "2.0.0", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
pallet-staking-reward-curve = { version = "2.0.0",  path = "../staking/reward-curve" }
substrate-test-utils = { version = "2.0.0" , git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
frame-benchmarking = { version = "2.0.0", git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev" }
rand_chacha = { version = "0.2" }
parking_lot = "0.10.2"
hex = "0.4"
pallet-assets-info = { path = '../assets-info', default-features = false, version = '2.0.0' }


[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-std/std",
	"sp-npos-elections/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"orml-tokens/std",
	"pallet-xyk/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]
