# Default values for mangata-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: "local"
domainZone: "mangata.online"
remoteCluster: false

replicas: 1

image:
  repository: mangatasolutions/mangata-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "rococo-0.25.0"

node:
  storageSize: "10Gi"
  env:
    RUST_LOG: "info"
  node_01:
    keys:
    - type: "aura"
      scheme: "sr25519"
      seed: "//Alice"
  node_02:
    keys:
    - type: "aura"
      scheme: "sr25519"
      seed: "//Bob"

relaychain:
  enabled: true
  image: "parity/polkadot:v0.9.29"
  storageSize: "10Gi"
  env:
    RUST_LOG: "info"

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
gcp:
  project: direct-pixel-353917