[package]
name = "sc-block-builder"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate block builder"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
log = "0.4.8"
sp-state-machine = "0.8.0"
sp-runtime = "2.0.0"
sp-api = "2.0.0"
sp-consensus = "0.8.0"
sp-blockchain = "2.0.0"
sp-core = "2.0.0"
sp-block-builder = "2.0.0"
sp-inherents = "2.0.0"
sp-std = { default-features = false, version = '2.0.0' }
sc-client-api = "2.0.0"
codec = { package = "parity-scale-codec", version = "1.3.4", features = ["derive"] }
rand = "0.7.3"

[dev-dependencies]
#substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
sp-trie = "2.0.0"


[features]
default = ['std']
std = [
    'sp-std/std',
]
