// This file is part of Mangata.

// Copyright (C) 2020-2022 Mangata Foundation.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for pallet_collective_mangata
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-20, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("mangata-kusama"), DB CACHE: 1024

// Executed Command:
// target/release/mangata-node
// benchmark
// pallet
// -l=info,runtime::collective=warn,xyk=warn
// --chain
// mangata-kusama
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// ./templates/module-weight-template.hbs
// --output
// ./benchmarks/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_collective_mangata.
pub trait WeightInfo {
	fn set_members(m: u32, n: u32, p: u32, ) -> Weight;
	fn execute(b: u32, m: u32, ) -> Weight;
	fn propose_execute(b: u32, m: u32, ) -> Weight;
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight;
	fn vote(m: u32, ) -> Weight;
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight;
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight;
	fn close_disapproved(m: u32, p: u32, ) -> Weight;
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight;
	fn disapprove_proposal(p: u32, ) -> Weight;
}

/// Weights for pallet_collective_mangata using the Mangata node and recommended hardware.
pub struct ModuleWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collective_mangata::WeightInfo for ModuleWeight<T> {
	// Storage: `Council::Members` (r:1 w:1)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:0)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:100 w:100)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:0 w:1)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		(Weight::from_parts(56_930_000, 0))
			// Standard Error: 75_983
			.saturating_add((Weight::from_parts(5_656_190, 0)).saturating_mul(m as u64))
			// Standard Error: 75_983
			.saturating_add((Weight::from_parts(10_752_628, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().reads((1 as u64).saturating_mul(p as u64)))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
			.saturating_add(T::DbWeight::get().writes((1 as u64).saturating_mul(p as u64)))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute(_b: u32, m: u32, ) -> Weight {
		(Weight::from_parts(32_347_546, 0))
			// Standard Error: 1_733
			.saturating_add((Weight::from_parts(20_109, 0)).saturating_mul(m as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:0)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		(Weight::from_parts(34_280_801, 0))
			// Standard Error: 220
			.saturating_add((Weight::from_parts(2_579, 0)).saturating_mul(b as u64))
			// Standard Error: 2_276
			.saturating_add((Weight::from_parts(45_962, 0)).saturating_mul(m as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalCount` (r:1 w:1)
	// Proof: `Council::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:0 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:0 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(49_638_444, 0))
			// Standard Error: 319
			.saturating_add((Weight::from_parts(4_413, 0)).saturating_mul(b as u64))
			// Standard Error: 3_330
			.saturating_add((Weight::from_parts(34_950, 0)).saturating_mul(m as u64))
			// Standard Error: 3_288
			.saturating_add((Weight::from_parts(344_067, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(5 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote(m: u32, ) -> Weight {
		(Weight::from_parts(48_255_187, 0))
			// Standard Error: 3_028
			.saturating_add((Weight::from_parts(59_613, 0)).saturating_mul(m as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(69_456_397, 0))
			// Standard Error: 4_288
			.saturating_add((Weight::from_parts(98_520, 0)).saturating_mul(m as u64))
			// Standard Error: 4_181
			.saturating_add((Weight::from_parts(345_792, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(94_575_321, 0))
			// Standard Error: 532
			.saturating_add((Weight::from_parts(8_199, 0)).saturating_mul(b as u64))
			// Standard Error: 5_623
			.saturating_add((Weight::from_parts(72_246, 0)).saturating_mul(m as u64))
			// Standard Error: 5_481
			.saturating_add((Weight::from_parts(403_035, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:1 w:0)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(75_627_064, 0))
			// Standard Error: 4_313
			.saturating_add((Weight::from_parts(82_419, 0)).saturating_mul(m as u64))
			// Standard Error: 4_206
			.saturating_add((Weight::from_parts(337_204, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:1 w:0)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(99_748_377, 0))
			// Standard Error: 568
			.saturating_add((Weight::from_parts(8_301, 0)).saturating_mul(b as u64))
			// Standard Error: 6_004
			.saturating_add((Weight::from_parts(54_155, 0)).saturating_mul(m as u64))
			// Standard Error: 5_853
			.saturating_add((Weight::from_parts(417_747, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(6 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:0 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:0 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn disapprove_proposal(p: u32, ) -> Weight {
		(Weight::from_parts(36_703_019, 0))
			// Standard Error: 2_935
			.saturating_add((Weight::from_parts(312_935, 0)).saturating_mul(p as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: `Council::Members` (r:1 w:1)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:0)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:100 w:100)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:0 w:1)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		(Weight::from_parts(56_930_000, 0))
			// Standard Error: 75_983
			.saturating_add((Weight::from_parts(5_656_190, 0)).saturating_mul(m as u64))
			// Standard Error: 75_983
			.saturating_add((Weight::from_parts(10_752_628, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().reads((1 as u64).saturating_mul(p as u64)))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
			.saturating_add(RocksDbWeight::get().writes((1 as u64).saturating_mul(p as u64)))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute(_b: u32, m: u32, ) -> Weight {
		(Weight::from_parts(32_347_546, 0))
			// Standard Error: 1_733
			.saturating_add((Weight::from_parts(20_109, 0)).saturating_mul(m as u64))
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:0)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		(Weight::from_parts(34_280_801, 0))
			// Standard Error: 220
			.saturating_add((Weight::from_parts(2_579, 0)).saturating_mul(b as u64))
			// Standard Error: 2_276
			.saturating_add((Weight::from_parts(45_962, 0)).saturating_mul(m as u64))
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalCount` (r:1 w:1)
	// Proof: `Council::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:0 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:0 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(49_638_444, 0))
			// Standard Error: 319
			.saturating_add((Weight::from_parts(4_413, 0)).saturating_mul(b as u64))
			// Standard Error: 3_330
			.saturating_add((Weight::from_parts(34_950, 0)).saturating_mul(m as u64))
			// Standard Error: 3_288
			.saturating_add((Weight::from_parts(344_067, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(4 as u64))
			.saturating_add(RocksDbWeight::get().writes(5 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote(m: u32, ) -> Weight {
		(Weight::from_parts(48_255_187, 0))
			// Standard Error: 3_028
			.saturating_add((Weight::from_parts(59_613, 0)).saturating_mul(m as u64))
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(69_456_397, 0))
			// Standard Error: 4_288
			.saturating_add((Weight::from_parts(98_520, 0)).saturating_mul(m as u64))
			// Standard Error: 4_181
			.saturating_add((Weight::from_parts(345_792, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(4 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(94_575_321, 0))
			// Standard Error: 532
			.saturating_add((Weight::from_parts(8_199, 0)).saturating_mul(b as u64))
			// Standard Error: 5_623
			.saturating_add((Weight::from_parts(72_246, 0)).saturating_mul(m as u64))
			// Standard Error: 5_481
			.saturating_add((Weight::from_parts(403_035, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(5 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:1 w:0)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(75_627_064, 0))
			// Standard Error: 4_313
			.saturating_add((Weight::from_parts(82_419, 0)).saturating_mul(m as u64))
			// Standard Error: 4_206
			.saturating_add((Weight::from_parts(337_204, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(5 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Members` (r:1 w:0)
	// Proof: `Council::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:1 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:1 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Prime` (r:1 w:0)
	// Proof: `Council::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:1 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		(Weight::from_parts(99_748_377, 0))
			// Standard Error: 568
			.saturating_add((Weight::from_parts(8_301, 0)).saturating_mul(b as u64))
			// Standard Error: 6_004
			.saturating_add((Weight::from_parts(54_155, 0)).saturating_mul(m as u64))
			// Standard Error: 5_853
			.saturating_add((Weight::from_parts(417_747, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(6 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
	// Storage: `Council::Proposals` (r:1 w:1)
	// Proof: `Council::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalProposedTime` (r:0 w:1)
	// Proof: `Council::ProposalProposedTime` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::Voting` (r:0 w:1)
	// Proof: `Council::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	// Storage: `Council::ProposalOf` (r:0 w:1)
	// Proof: `Council::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn disapprove_proposal(p: u32, ) -> Weight {
		(Weight::from_parts(36_703_019, 0))
			// Standard Error: 2_935
			.saturating_add((Weight::from_parts(312_935, 0)).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(4 as u64))
	}
}
