relaychain:
  image: parity/polkadot:v0.9.27
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
        hrmp_channel_max_capacity: 1000
        hrmp_channel_max_total_size: 102400
        hrmp_channel_max_message_size: 102400
    hrmp:
      preopenHrmpChannels: [
        [ 2114, 2110, 1000, 102400 ], # oak -> mangata
        [ 2110, 2114, 1000, 102400 ], # mangata -> oak
      ]

  env:
    RUST_LOG: x_tokens=trace,xcm=trace,xcmp_queue=trace,runtime=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob

parachains:
  - image: mangatasolutions/mangata-node:dev
    chain:
      base: mangata-rococo-local
      collators:
        - alice
        - bob
      sudo: alice
    skipCollatorSelection: true
    skipBalances: true
    id: 2110
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: x_tokens=trace,xcm=trace,xcmp_queue=trace,runtime=trace
    volumePath: /mangata/data
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob

  - image: oaknetwork/neumann:1.7.0
    chain:
      base: dev
      collators:
        - alice
        - bob
      sudo: alice
    skipCollatorSelection: true
    id: 2114
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: x_tokens=trace,xcm=trace,xcmp_queue=trace,runtime=trace
    volumePath: /data
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
