{{- range $keys := .Values.node.node_02.keys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "node-02-{{ .type }}"
data:
  type: {{ .type | b64enc }}
  scheme: {{ .scheme | b64enc }}
  seed: {{ .seed | b64enc }}
{{- end }}