{{- if .Values.relaychain.enabled -}}
{{ $name :=  "relaychain-alice" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels: {{- include "node.labels" . | nindent 4 }}
    service: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
      service: {{ $name }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "node.labels" . | nindent 8 }}
        service: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ .Values.relaychain.image | quote }}
          command:
            - /usr/bin/polkadot
            - --validator
            - --port=30333
            - --ws-port=9944
            - --chain=/app/rococo-local.json
            - --unsafe-ws-external
            - --rpc-port=40333
            - --unsafe-rpc-external
            - --rpc-cors=all
            - --node-key=0000000000000000000000000000000000000000000000000000000000000001
            - "--public-addr=/dns4/{{ $name }}.{{ .Values.env }}.{{ .Values.domainZone }}/tcp/30333"
            - "--alice"
          ports:
            - containerPort: 30333
            - containerPort: 40333
            - containerPort: 9944
          env:
            {{- range $key, $val := .Values.relaychain.env }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /polkadot/.local/share/polkadot
              name: chaindata
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: chaindata
      spec:
        storageClassName: "standard-rwo"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.relaychain.storageSize }}
{{- end }}
