apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-01
  labels: {{- include "node.labels" . | nindent 4 }}
    service: node-01
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
      service: node-01
  serviceName: node-01
  template:
    metadata:
      labels:
        {{- include "node.labels" . | nindent 8 }}
        service: node-01
    spec:
      initContainers:
        - name: chainspec-generator
          image: {{ .Values.relaychain.image | quote }}
          command: ["/bin/bash"]
          args: 
            - -c
            - /usr/bin/polkadot build-spec --chain=rococo-local --disable-default-bootnode --raw > /etc/mangata/local.json
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
        - name: export-genesis-wasm-and-state
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          command: ["/bin/bash"]
          args: 
            - -c
            - |
              set -eu
              /mangata/node export-genesis-state --chain=public-testnet > /etc/mangata/genesis-state
              /mangata/node export-genesis-wasm --chain=public-testnet > /etc/mangata/genesis-wasm
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
        - name: inject-keys
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/bash"]
          args:
            - -c
            - |
              set -eu
              {{- range $keys := .Values.node.node_01.keys }}
              if [ ! -f /var/run/secrets/{{ .type }}/type ]; then
                 echo "Error: File /var/run/secrets/{{ .type }}/type does not exist"
                 exit 1
              fi
              /mangata/node key insert --chain public-testnet --keystore-path /keystore \
              --key-type $(cat /var/run/secrets/{{ .type }}/type) \
              --scheme $(cat /var/run/secrets/{{ .type }}/scheme) \
              --suri /var/run/secrets/{{ .type }}/seed \
              && echo "Inserted key {{ .type }} into Keystore" \
              || echo "Failed to insert key {{ .type}} into Keystore."
              {{- end }}
          volumeMounts:
            - mountPath: /keystore
              name: chain-keystore
          {{- range $keys := .Values.node.node_01.keys }}
            - mountPath: /var/run/secrets/{{ .type }}
              name: {{ .type }}
          {{- end }}
      containers:
        - name: node-01
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command:
            # parachain
            - /mangata/node
            - --name=node-01
            - --chain=public-testnet
            - --base-path=/mangata/data
            - --keystore-path=/keystore
            - --collator
            - --force-authoring
            - --port=30333
            - --ws-port=9944
            - --rpc-port=9933
            - --prometheus-port=9716
            - --unsafe-ws-external
            - --unsafe-rpc-external
            - --prometheus-external
            - --rpc-methods=Unsafe
            - --rpc-cors=all
            - --node-key=0000000000000000000000000000000000000000000000000000000000000003
            {{- if .Values.remoteCluster }}
            - "--public-addr=/dns4/node-01-{{ .Values.env }}.{{ .Values.domainZone }}/tcp/30333"
            {{- end }}
            - --
            # relaychain
            - --base-path=/mangata/relaychaindata
            - --bootnodes=/dns/relaychain-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
            - --execution=wasm
            - --chain=/etc/mangata/local.json
          ports:
            - containerPort: 9716
            - containerPort: 9944
            - containerPort: 30333
            - containerPort: 40333
          env:
            {{- range $key, $val := .Values.node.env }}
            - name: {{ $key }}
              value: {{ $val }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
            - mountPath: /keystore
              name: chain-keystore
            - mountPath: /mangata/data
              name: chaindata            
            - mountPath: /mangata/relaychaindata
              name: relaychaindata
        {{- if .Values.node.enableParachainRegisterSidecar }}
        - name: parachain-register-sidecar
          image: mangatasolutions/parachain-register:1.0
          command:
            - "bash"
            - "-c"
            - "node index.js"
          env:
            - name: STATE_FILE
              value: /etc/mangata/genesis-state
            - name: WASM_FILE
              value: /etc/mangata/genesis-wasm
            - name: COLLATOR_ADDR
              value: ws://relaychain-alice:9944
            - name: PARA_ID
              value: "2110"
          volumeMounts:
            - mountPath: /etc/mangata/
              name: node-chainspec-volume
        {{- end }}
      volumes:
        - name: node-chainspec-volume
          emptyDir: {}
        - name: chain-keystore
          emptyDir:
            medium: "Memory"
            sizeLimit: 10Mi
      {{- range $keys := .Values.node.node_01.keys }}
        - name: {{ .type }}
          secret:
            secretName: "node-01-{{ .type }}"
            defaultMode: 0400
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: chaindata
      spec:
        storageClassName: "standard-rwo"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.node.storageSize }}
    - metadata:
        name: relaychaindata
      spec:
        storageClassName: "standard-rwo"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.node.relaychainStorageSize }}
