repositories:
  - name: mangata
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=feat/MGX-241-node-chart

environments:
  default:
    values:
      - node01KeySeed: ref+gcpsecrets://direct-pixel-353917/node-01-key-seed-dev
      - node02KeySeed: ref+gcpsecrets://direct-pixel-353917/node-02-key-seed-dev

releases:
  - name: relaychain
    namespace: testm
    chart: mangata/relaychain-testnet
    wait: true
    values:
      - env: testm
        remoteCluster: true
  - name: node-01
    namespace: testm
    chart: mangata/node
    wait: true
    values:
      - env: testm
        remoteCluster: true
        node:
          parachainRegisterSidecar:
            enable: true
          nodeKey: '0000000000000000000000000000000000000000000000000000000000000003'
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node01KeySeed | fetchSecretValue | quote }}
  - name: node-02
    namespace: testm
    chart: mangata/node
    wait: true
    values:
      - env: testm
        remoteCluster: true
        node:
          bootnodeAddr: /dns4/node-01/tcp/30333/p2p/12D3KooWSCufgHzV4fCwRijfH2k3abrpAJxTKxEvN1FDuRXA2U9x
          parachainRegisterSidecar:
            enable: false
          nodeKey: '0000000000000000000000000000000000000000000000000000000000000004'
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node02KeySeed | fetchSecretValue | quote }}        
