repositories:
  - name: mangata
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=feat/MGX-241-node-chart

environments:
  dev:
    values:
      - "./config/dev.yaml"
  fungible:
    values:
      - "./config/fungible.yaml"
  rococo:
    values:
      - "./config/rococo.yaml"

helmDefaults:
  wait: true

releases:
  - name: relaychain
    installed: {{ .Values.enableLocalRelaychain | toYaml }}
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/relaychain-testnet
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        storageSize: {{ .Values.relaychainStorageSize }}
        remoteCluster: true
  - name: node-01
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/node
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: true
        node:
          storageSize: {{ .Values.storageSize }}
          relaychainStorageSize: {{ .Values.relaychainStorageSize }}
          parachainRegisterSidecar:
            enable: true
          nodeKey: {{ .Values.node01.nodeKey | quote }}
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node01.accountKeySeed | fetchSecretValue | quote }}
  - name: node-02
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/node
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: true
        node:
          bootnodeAddr: {{ .Values.followerBootnodeAddr | quote }}
          storageSize: {{ .Values.storageSize }}
          relaychainStorageSize: {{ .Values.relaychainStorageSize }}
          parachainRegisterSidecar:
            enable: false
          nodeKey: {{ .Values.node02.nodeKey | quote }}
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node02.accountKeySeed | fetchSecretValue | quote }}
  - name: node-03
    installed: {{ .Values.node03.enabled | toYaml }}
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/node
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: true
        node:
          bootnodeAddr: {{ .Values.followerBootnodeAddr | quote }}
          storageSize: {{ .Values.storageSize }}
          relaychainStorageSize: {{ .Values.relaychainStorageSize }}
          parachainRegisterSidecar:
            enable: false
          nodeKey: {{ .Values.node03.nodeKey | quote }}
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node03.accountKeySeed | fetchSecretValue | quote }}
