environments:
  dev:
    values:
      - ./config/default.yaml
      - ./config/dev.yaml
  fungible:
    values:
      - ./config/default.yaml
      - ./config/fungible.yaml
  release:
    values:
      - ./config/default.yaml
      - ./config/release.yaml
---
repositories:
  - name: mangata-node
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=node-v2.3.0

helmDefaults:
  wait: true

releases:
  - name: node-01
    chart: mangata-node/node
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    values:
      - values.yaml.gotmpl
      - # Identity ID: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
        customNodeKey: '0000000000000000000000000000000000000000000000000000000000000001'
        bootnodeAddr: /dns/node-02/tcp/30333/p2p/12D3KooWFz4zM26EKYTpX98GhLhS3KLv7mUyvpYXCdzxdrorSVCu
        extraArgs:
          - --alice
  - name: node-02
    chart: mangata-node/node
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    values:
      - values.yaml.gotmpl
      - # Identity ID: 12D3KooWFz4zM26EKYTpX98GhLhS3KLv7mUyvpYXCdzxdrorSVCu
        customNodeKey: 'bcaf1bb787b48156aadaf318603e5b37e637883edafb850912e364e913e2c35b'
        bootnodeAddr: /dns/node-01/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
        extraArgs:
          - --bob
