environments:
  dev:
    values:
      - ./config/default.yaml
      - ./config/dev.yaml
  fungible:
    values:
      - ./config/default.yaml
      - ./config/fungible.yaml
  release:
    values:
      - ./config/default.yaml
      - ./config/release.yaml
---
repositories:
  - name: mangata-node
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=node-v1.0.0
  - name: mangata-relaychain
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=relaychain-testnet-v1.0.0


helmDefaults:
  wait: true

templates:
  nodeDefault: &nodeDefault
    chart: mangata-node/node
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'

releases:
  - name: relaychain
    installed: {{ .Values.enableLocalRelaychain | toYaml }}
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata-relaychain/relaychain-testnet
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        storageClass: node-data-volume
        storageSize: {{ .Values.relaychainStorageSize }}
        remoteCluster: true
  - name: node-01
    <<: *nodeDefault
    values:
      - values.yaml.gotmpl
      - isCollator: {{ .Values.node01.isCollator  | toYaml }}
        parachainRegisterSidecar:
          enable: {{ .Values.enableParachainRegisterSidecar  | toYaml }}
        bootnodeAddr: {{ .Values.node01.bootnodeAddr }}
        customNodeKey: {{ .Values.node01.nodeKey | fetchSecretValue | quote }}
        accountKeys:
          - type: aura
            scheme: sr25519
            seed: {{ .Values.node01.accountKeySeed | fetchSecretValue | quote }}
  - name: node-02
    <<: *nodeDefault
    values:
      - values.yaml.gotmpl
      - isCollator: {{ .Values.node02.isCollator  | toYaml }}
        bootnodeAddr: {{ .Values.node02.bootnodeAddr }}
        customNodeKey: {{ .Values.node02.nodeKey |fetchSecretValue | quote }}
        accountKeys:
          - type: aura
            scheme: sr25519
            seed: {{ .Values.node02.accountKeySeed | fetchSecretValue | quote }}
