repositories:
  - name: mangata
    url: git+https://github.com/mangata-finance/helm-charts@charts?ref=feat/MGX-241-node-chart

environments:
  fungible:
    values:
      - "./config/values-fungible.yaml"

releases:
  - name: relaychain
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/relaychain-testnet
    wait: true
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        remoteCluster: true
  - name: node-01
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/node
    wait: true
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: true
        node:
          parachainRegisterSidecar:
            enable: true
          nodeKey: {{ .Values.node01NodeKey | quote }}
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node01KeySeed | fetchSecretValue | quote }}
  - name: node-02
    namespace: '{{ requiredEnv "ENVIRONMENT" }}'
    chart: mangata/node
    wait: true
    values:
      - env: {{ requiredEnv "ENVIRONMENT" | quote }}
        image:
          tag: {{ requiredEnv "IMAGE_TAG" | quote }}
        remoteCluster: true
        node:
          bootnodeAddr: {{ .Values.bootnodeAddr | quote }}
          parachainRegisterSidecar:
            enable: false
          nodeKey: {{ .Values.node02NodeKey | quote }}
          accountKeys:
            - type: aura
              scheme: sr25519
              seed: {{ .Values.node02KeySeed | fetchSecretValue | quote }}        
