---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: websocket
spec:
  # Custom Health Check is required to make GKE Ingress Load Balancer pass traffic
  healthCheck:
    timeoutSec: 1
    type: HTTP
    requestPath: /health
    port: 40333
  # Configurations required for WebSocket connections not to get dropped every 30s
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800