apiVersion: v1
kind: Service
metadata:
  name: relaychain-alice
  annotations:
    cloud.google.com/backend-config: '{"default": "websocket"}'
  labels: {{- include "mangata-node.labels" . | nindent 4 }}
    service: relaychain-alice
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 30333
      name: p2p-port
    - port: 40333
      name: http-rpc
    - port: 9944
      name: http-ws
  selector:
    {{- include "mangata-node.selectorLabels" . | nindent 4 }}
    service: relaychain-alice