apiVersion: v1
kind: Service
metadata:
  name: relaychain-bob
  labels: {{- include "mangata-node.labels" . | nindent 4 }}
    service: relaychain-bob
spec:
  ports:
    - port: 30333
      name: p2p-port
    - port: 40333
      name: http-rpc
    - port: 9944
      name: http-ws
  selector:
    {{- include "mangata-node.selectorLabels" . | nindent 4 }}
    service: relaychain-bob
