{{- if .Values.relaychain.enabled -}}
{{ $name :=  "relaychain-bob" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels: {{- include "node.labels" . | nindent 4 }}
    service: {{ $name }}
spec:
  ports:
    - port: 30333
      name: p2p-port
    - port: 40333
      name: http-rpc
    - port: 9944
      name: http-ws
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}
    service: {{ $name }}
{{- end }}
