name: Production Release Workflow

on:
  pull_request:
    # branches: [main]
    # types: [closed]

jobs:
  init:
    name: Global init
    # if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'rc/')
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.set_vars.outputs.RELEASE_VERSION }}
    steps:
      - name: Set release version
        id: set_vars
        run: echo "RELEASE_VERSION=0.0.0" >> $GITHUB_OUTPUT
        # run: echo "RELEASE_VERSION=${GITHUB_HEAD_REF#rc/}" >> $GITHUB_OUTPUT
  
  build-and-test:
    needs: [init]
    name: Build
    uses: ./.github/workflows/reusable-build-and-test.yml
    secrets: inherit
    with:
      version: ${{ needs.init.outputs.RELEASE_VERSION }}
      # branch: 'main'
      branch: 'test'
  
  run-e2e-tests:
    name: Run e2e tests
    needs: [init,build-and-test]
    uses: ./.github/workflows/reusable-e2e-tests.yml
    secrets: inherit
    with:
      globalVersion: ${{ needs.init.outputs.RELEASE_VERSION }}

  
  publish-rococo-image:
    needs: [init,build-and-test]
    environment: rococo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mangatasolutions/mangata-node:${{ needs.init.outputs.RELEASE_VERSION }}
          dst: docker.io/mangatasolutions/mangata-node:rococo-${{ needs.init.outputs.RELEASE_VERSION }}

  deploy-rococo:
    needs: [init,publish-rococo-image]
    if: false
    name: Deploy to Rococo
    uses: ./.github/workflows/reusable-deploy-rococo.yml
    with:
      version: rococo-${{ needs.init.outputs.RELEASE_VERSION }}
  
  publish-kusama-image:
    needs: [init,deploy-rococo]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: docker.io/mangatasolutions/mangata-node:${{ needs.init.outputs.RELEASE_VERSION }}
          dst: docker.io/mangatasolutions/mangata-node:kusama-${{ needs.init.outputs.RELEASE_VERSION }}

  deploy-kusama:
    needs: [init,publish-kusama-image]
    name: Deploy to Kusama
    uses: ./.github/workflows/reusable-deploy-kusama.yml
    with:
      version: kusama-${{ needs.init.outputs.RELEASE_VERSION }}

