name: Deploy mangata-node to `rococo`

on:
  push:
    branches: [feat/add-rococo-deployment-workflow-mgx-241]

jobs:
  deploy_rococo:
    name: Deploy `rococo` environment
    environment: rococo
    uses: ./.github/workflows/reusable-deploy-prod.yml
    secrets: inherit
    with:
      version: rococo-0.27.2
