name: deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment for deployment"
        required: true
        type: string
      version:
        description: "Version to be assigned to the built image"
        required: true
        type: string
      cluster_name:
        description: "Name of the cluster on which to perform deployment"
        default: mangata-dev
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.8.0
        with:
          cluster_name: ${{ inputs.cluster_name }}
          location: europe-west1
      
      - uses: jkroepke/setup-vals@v1.0.4
      - run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v4.1.1
          helm secrets -b vals upgrade -i --create-namespace -n ${{ inputs.environment }} --wait node . \
          --set image.tag=${{ inputs.version }} \
          -f values.yaml -f values-dev.yaml
        working-directory: devops/helm-charts/node
