name: deploy
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'mangata-dev'
          location: 'europe-west1'
     
      - id: 'get-pods'
        run: kubectl get pods
