name: deploy
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

env:
  version: dev

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.8.0
        with:
          cluster_name: mangata-dev
          location: europe-west1
      
      - uses: jkroepke/setup-vals@v1.0.4
      - run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v4.1.1
          helm secrets -b vals upgrade -i --create-namespace -n ${{ env.version }} --wait node . \
          -f values.yaml -f values-dev.yaml
        working-directory: devops/helm-charts/node
