name: Deploy docs

on:
  push:
    # TODO: temporary for test - to be removed
    branches: [develop, ci/workflow-fixes]

jobs:
  docs:
    permissions:
      contents: write
      id-token: write
    runs-on: [compile-gke]
    container:
      image: mangatasolutions/node-builder:multi-nightly-2023-05-22
    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - name: Cache the Cargo dependencies
        uses: mansagroup/gcs-cache-action@v1.0.3
        with:
          bucket: mangata-node-ci-cache
          path: |
            ${{ github.workspace }}/target
            /usr/local/cargo/git
            /usr/local/cargo/registry
            ~/.cache/sccache
          key: node-docs-cache-1-${{ hashFiles('Cargo.lock') }}
      
      - name: Build docs
        run: cargo doc
      
      - name: Deploy to GCP
        uses: google-github-actions/upload-cloud-storage@v2.1.0
        with:
          path: ./target/doc/
          destination: mangata-docs-node
          parent: false
          concurrency: 50
          process_gcloudignore: false