name: Deploy docs

on:
  push:
    branches: [ develop ]

env:
  DOCKER_BUILDER_IMAGE: mangatasolutions/node-builder:0.2
  DISABLE_TTY: 1

jobs:
  docs:
    permissions:
      contents: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull builder image
        run: |
          docker pull ${{ env.DOCKER_BUILDER_IMAGE }}
      - name: Build docs
        run: |
          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
          ./docker-cargo.sh doc
      - name: 'Deploy to GCP'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './docker-cargo/doc/'
          destination: 'mangata-docs-node'
          parent: false
