name: Deploy docs

on:
  push:
    branches: [ develop ]

jobs:
  docs:
    permissions:
      contents: write
      id-token: write
    runs-on: [self-hosted, compile]
    container:
      image: mangatasolutions/node-builder:multi-nightly-2022-11-21
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Cache the Cargo dependencies
        uses: mansagroup/gcs-cache-action@v1.0.3
        with:
          bucket: mangata-node-ci-cache
          path: |
            ${{ github.workspace }}/target
            /usr/local/cargo/git
            /usr/local/cargo/registry
            ~/.cache/sccache
          key: node-docs-cache-0-${{ hashFiles('Cargo.lock') }}
      
      - name: Build docs
        run: cargo doc
      
      - name: Deploy to GCP
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          path: ./target/doc/
          destination: mangata-docs-node
          parent: false
      
      - name: Fix permissions on self-hosted runner
        if: always()
        run: chown -R 1004:1005 $GITHUB_WORKSPACE
        
