name: Deploy docs

on:
  push:
    branches: [ develop, 'ci/fix-docs-workflow-MGX-664' ]

jobs:
  docs:
    permissions:
      contents: write
      id-token: write
    runs-on: mangata-node-e2e-runners
    container:
      image: mangatasolutions/node-builder:multi-nightly-2022-11-15
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Cache the Cargo dependencies
        uses: mansagroup/gcs-cache-action@v1.0.3
        with:
          bucket: mangata-node-ci-cache
          path: |
            ${{ github.workspace }}/target
            /usr/local/cargo/git
            /usr/local/cargo/registry
            ~/.cache/sccache
          key: node-docs-cache-1-${{ hashFiles('Cargo.lock') }}
      
      - name: Build docs
        run: cargo doc
      
      - name: Deploy to GCP
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          path: ./target/doc/
          destination: mangata-docs-node
          parent: false
          concurrency: 50
          process_gcloudignore: false
      
      - name: Fix permissions on self-hosted runner
        if: always()
        run: chown -R 1100:1100 $GITHUB_WORKSPACE