name: Deploy docs

on:
  push:
    branches: [ develop ]

jobs:
  docs:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Pull builder image
        run: docker pull mangatasolutions/node-builder:0.2
      - name: Build docs
        run: |
          ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch || ./docker-cargo.sh fetch
          ./docker-cargo.sh doc
      
      - name: Deploy to GCP
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          path: ./docker-cargo/doc/
          destination: mangata-docs-node
          parent: false
