name: Deploy docs

on:
  push:
    branches: [ develop ]
  pull_request:

# The following concurrency group cancels in-progress jobs or runs on pull_request events only
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: write
      id-token: write
    runs-on: [self-hosted, compile]
    container:
      image: mangatasolutions/node-builder:multi-nightly-2022-11-15
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Cache the Cargo dependencies
        uses: mansagroup/gcs-cache-action@v1.0.3
        with:
          bucket: mangata-node-ci-cache
          path: |
            ${{ github.workspace }}/target
            /usr/local/cargo/git
            /usr/local/cargo/registry
            ~/.cache/sccache
          key: node-docs-cache-0-${{ hashFiles('Cargo.lock') }}
      
      - name: Build docs
        run: cargo doc
      
      - name: Deploy to GCP
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          path: ./target/doc/
          destination: mangata-docs-node
          parent: false
