name: Performance tests workflow
on:
  workflow_call:
    inputs:
      e2eBranch:
        description: "Name of the e2e target branch"
        type: string
        required: false
        default: "main"
      targetEnv:
        description: "env name"
        type: string
        required: false

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

jobs:
  performance-tests:
    # Allows to keep e2e tests jobs running even if performance-tests fail
    continue-on-error: true
    runs-on: [compile-gke]
    timeout-minutes: 180
    env:
      ENV_REF: ${{ inputs.targetEnv || format('pr-{0}', github.event.number) }}
      E2EBRANCHNAME: "main"
    steps:
      ####IDK, but this is neccesary for reports
      - uses: actions/checkout@v3

      - name: E2E- Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: Set Configuration - Develop
        if: "${{ inputs.targetEnv == 'dev' }}"
        run: |
          echo 'TEST_SUDO_NAME=${{ secrets.DEV_SUDO_NAME }}' >> $GITHUB_ENV

      - name: E2E- Calculate if run e2e feature branch or main.
        run: |
          echo DEFAULT: E2E test will run with: $E2EBRANCHNAME
          echo "Running on: ${{ steps.branch-name.outputs.current_branch }}"
          if [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ steps.branch-name.outputs.current_branch }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV; echo "MATCH - OK" ; elif [ -n "$(git ls-remote --heads https://github.com/mangata-finance/mangata-e2e.git ${{ github.base_ref }} --force --quiet)" ]; then echo "E2EBRANCHNAME=${{ github.base_ref }}" >> $GITHUB_ENV; echo "MATCH - OK" ;  fi

      - name: Decide if main - branch or parameter
        # if we have something in e2eBranch - override E2EBranchName, else -> E2EBRANCHNAME , that
        # by default will be main.
        run: echo "E2EBRANCHNAME=${{ inputs.e2eBranch || env.E2EBRANCHNAME }}" >> $GITHUB_ENV

      - name: Checkout performance-tests
        uses: actions/checkout@v3
        with:
          repository: mangata-finance/mangata-e2e
          ref: "${{ env.E2EBRANCHNAME }}"
          path: e2e

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install e2e tests dependencies
        working-directory: e2e
        run: yarn

      - name: Run performance tests
        working-directory: e2e/performance
        run: |
          node --experimental-specifier-resolution=node --loader ts-node/esm --experimental-vm-modules index.ts \
          transfer \
          nodes="wss://node-01-ws-${{ env.ENV_REF }}.mangata.online" \
          testCaseName=ConcurrentTest \
          pending=2000 \
          threadNumber=12 \
          duration=50 \
          throughput=200

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: performance-benchmarks-report
          path: |
            ./e2e/performance/report.html
            ./e2e/performance/enqueued.txt
            ./e2e/performance/executed.txt
            ./e2e/performance/pending.txt
