name: Performance tests workflow
on:
  workflow_call:

permissions:
  contents: write
  id-token: write
  deployments: write
  checks: write

jobs:
  performance-tests:
    runs-on: [self-hosted, compile]
    timeout-minutes: 180
    env:
      ENV_REF: ${{ inputs.env == 'fungible' && format('pr-{0}', github.event.number) || inputs.env }}
      TEST_SUDO_NAME: "//Alice"
    steps:
      ####IDK, but this is neccesary for reports
      - uses: actions/checkout@v3

      - name: Checkout performance-tests
        uses: actions/checkout@v3
        with:
          repository: mangata-finance/dev-tools
          path: dev-tools

      - name: Install parachain launch
        working-directory: dev-tools/fill-txs
        run: npm install

          # "https://polkadot.js.org/apps/?rpc=wss://node-01-ws-${{ env.ENV_REF }}.mangata.online#/explorer"
